# Navidrome Configuration File

# Music folder - where your music files are stored
MusicFolder = "/music"

# Data folder - where Navidrome stores its database and cache
DataFolder = "/data"

# Port to bind the server (Render requires this to be from PORT env var)
Port = "${PORT}"

ArtistArtPriority = "folder.*, artist.*, album/artist.*, external"

# Log level
LogLevel = "info"

# Scanner settings to reduce unnecessary scans
ScanSchedule = "@every 24h"

# Disable automatic scanning on startup
AutoImportPlaylists = true

# Database - Navidrome uses SQLite by default (stored in DataFolder)
# No additional database server needed

# Session timeout
SessionTimeout = "24h"

# Enable transcoding (optional)
EnableTranscodingConfig = true

# Reduce resource usage
Scanner.Extractor = "taglib"

# --------------------------
# Admin API key (for /api/* endpoints)
# --------------------------
ApiKey = "your-random-long-string"

UILoginBackgroundUrl="https://images.unsplash.com/photo-1646038572815-43fe759e459b?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&q=80&w=774"
